<a href="https://colab.research.google.com/github/syhennie/data-quality-process/blob/main/features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Настройка окружения

In [1]:
%pip install numpy gensim pandas scipy sdv matplotlib

Requirement already satisfied: numpy in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (2.3.5)
Requirement already satisfied: gensim in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (4.4.0)
Requirement already satisfied: pandas in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: scipy in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (1.16.3)
Requirement already satisfied: sdv in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (1.29.1)
Requirement already satisfied: matplotlib in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (3.10.7)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from gensim) (7.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: boto3<2.0.0,>=1.28 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.42.0)
Requirement already satisfied: botocore<2.0.0,>=1.31 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.41.6)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.21)
Requirement already satisfied: tqdm>=4.29 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.67.1)
Requirement already satisfied: copulas>=0.12.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.12.3)
Requirement already satisfied: ctgan>=0.11.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.11.1)
Requirement already satisfied: deepecho>=0.7.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.7.0)
Requirement already satisfied: rdt>=1.18.2 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.18.2)
Requirement already satisfied: sdmetrics>=0.21.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (0.24.0)
Requirement already satisfied: platformdirs>=4.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from sdv) (4.5.0)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sdv) (6.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from boto3<2.0.0,>=1.28->sdv) (0.16.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (6.5.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from ctgan>=0.11.0->sdv) (2.9.0+cu130)
Requirement already satisfied: six>=1.5 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn>=1.1.3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.18.2->sdv) (1.7.2)
Requirement already satisfied: Faker!=37.11.0,>=17 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.18.2->sdv) (38.2.0)
Requirement already satisfied: wrapt in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Requirement already satisfied: colorama in c:\users\stepa\appdata\roaming\python\python311\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (2.13.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\stepa\appdata\roaming\python\python311\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.6)
Requirement already satisfied: jinja2 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.0->sdv) (2025.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.0->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\stepa\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.0->sdv) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

## Предобучение модели векторизации

In [3]:
from gensim.models.fasttext import FastText
from gensim.test.utils import datapath

VECTOR_SIZE = 64

In [ ]:
# Set file names for train and test data
corpus_file = datapath('lee_background.cor')

model = FastText(vector_size=VECTOR_SIZE)

# build the vocabulary
model.build_vocab(corpus_file=corpus_file)

# train the model
model.train(
    corpus_file=corpus_file, epochs=model.epochs,
    total_examples=model.corpus_count, total_words=model.corpus_total_words,
)

with open("../fasttext_lee_background", "w") as file:
    model.save(file.name)

## Загрузка и предобработка данных

In [4]:
df = pd.read_csv('../test.csv')
df.head()

,id,article,highlights
0,92c514c913c0bdfe25341af9fd72b29db544099b,Ever noticed how plane seats appear to be gett...,Experts question if packed out planes are put...
1,2003841c7dc0e7c5b1a248f9cd536d727f27a45a,A drunk teenage boy had to be rescued by secur...,Drunk teenage boy climbed into lion enclosure ...
2,91b7d2311527f5c2b63a65ca98d21d9c92485149,Dougie Freedman is on the verge of agreeing a ...,Nottingham Forest are close to extending Dougi...
3,caabf9cbdf96eb1410295a673e953d304391bfbb,Liverpool target Neto is also wanted by PSG an...,Fiorentina goalkeeper Neto has been linked wit...
4,3da746a7d9afcaa659088c8366ef6347fe6b53ea,Bruce Jenner will break his silence in a two-h...,"Tell-all interview with the reality TV star, 6..."

In [5]:
df = df.iloc[:, 1:]
df.dropna()
df

,article,highlights
0,Ever noticed how plane seats appear to be gett...,Experts question if packed out planes are put...
1,A drunk teenage boy had to be rescued by secur...,Drunk teenage boy climbed into lion enclosure ...
2,Dougie Freedman is on the verge of agreeing a ...,Nottingham Forest are close to extending Dougi...
3,Liverpool target Neto is also wanted by PSG an...,Fiorentina goalkeeper Neto has been linked wit...
4,Bruce Jenner will break his silence in a two-h...,"Tell-all interview with the reality TV star, 6..."
...,...,...
11485,Our young Earth may have collided with a body ...,Oxford scientists say a Mercury-like body stru...
11486,A man facing trial for helping his former love...,Man accused of helping former lover kill woman...
11487,A dozen or more metal implements are arranged ...,Marianne Power tried the tuning fork facial at...
11488,Brook Lopez dominated twin brother Robin with ...,Brooklyn Nets beat the Portland Trail Blazers ...
11489,A Chinese hospital is being painstakingly move...,Chinese hospital marked for demolition because...

## Извлечение свойств из набора данных

In [6]:
from gensim.models import Word2Vec, FastText
from gensim.utils import simple_preprocess

model = FastText.load("../fasttext_lee_background")

MAX_TOKENS_PER_ENTRY = 32

def get_vectorised_entries(entries):
    features = []
    for entry in entries:
        tokens = simple_preprocess(entry, min_len=1)
        vectors = [model.wv[token] for token in tokens]
        features.append(np.mean(vectors, axis=0))
    return np.array(features)

def vectorise_entries(entries):
    features = []
    for entry in entries:
        tokens = simple_preprocess(entry)
        vectors = [model.wv[token] for token in tokens]
        length = min(len(vectors), MAX_TOKENS_PER_ENTRY)
        trimmed_vectors = vectors[:length]
        if length < MAX_TOKENS_PER_ENTRY:
            padding_vectors = [np.zeros(VECTOR_SIZE) for _ in range(MAX_TOKENS_PER_ENTRY - length)]
            trimmed_vectors += padding_vectors
        features.append(np.concatenate(trimmed_vectors))
    return np.array(features)

In [7]:
summary_stats = []
features_data = []

df_sample = df.sample(1000)

def calculate_stats(dataframe):
    summary_stats = []
    features_data = []
    for column in dataframe.columns:
        entries = [x for x in dataframe[column]]
        features = get_vectorised_entries(entries)
        vectorised_entries = vectorise_entries(entries)

        # Features-based metrics
        #
        # mean = np.mean(features, axis=0)
        # standard_deviation = np.std(features, axis=0)
        # median = np.median(features, axis=0)
        # asymmetry = stats.skew(features, axis=0)
        # excess = stats.kurtosis(features, axis=0)

        mean = np.mean(vectorised_entries, axis=0)
        standard_deviation = np.std(vectorised_entries, axis=0)
        median = np.median(vectorised_entries, axis=0)
        asymmetry = stats.skew(vectorised_entries, axis=0)
        excess = stats.kurtosis(vectorised_entries, axis=0)

        summary_stats.append({
            'column': column,
            'overall_mean': np.mean(mean),
            'overall_std': np.mean(standard_deviation),
            'std_of_means': np.std(mean),
            'mean_of_medians': np.mean(median),
            'asymmetry_avg': np.mean(asymmetry),
            'excess_avg': np.mean(excess),
            'n_entries': len(entries),
            'vector_dim': vectorised_entries.shape[1]
        })

        features_data.append({
                'column': column,
                'vectors': features
            })
        
    return summary_stats

summary_df = pd.DataFrame(calculate_stats(df_sample))
stats_df = pd.DataFrame(calculate_stats(df))

stats_df

,column,overall_mean,overall_std,std_of_means,mean_of_medians,asymmetry_avg,excess_avg,n_entries,vector_dim
0,article,-0.034556,0.191570,0.431112,-0.032743,-0.061589,-0.273300,11490,2048
1,highlights,-0.032811,0.198002,0.410376,-0.030477,-0.068840,-0.161357,11490,2048

## Генерация синтетического набора данных

In [8]:
def generate_synthetic_vectors(summary_df, method):
    synthetic_data = []

    for i, row in summary_df.iterrows():
        print(i)
        n_samples = row['n_entries']
        vector_dim = row['vector_dim']

        if method == 'normal':
            mean_vector = np.full(vector_dim, row['overall_mean'])
            cov_matrix = np.eye(vector_dim) * (row['std_of_means'] ** 2)

            synthetic_vectors = stats.multivariate_normal.rvs(
                mean=mean_vector,
                cov=cov_matrix,
                size=n_samples
            )

        elif method == 'statistical_adjustment':
            base_vectors = np.random.normal(
                loc=row['overall_mean'],
                scale=row['overall_std'],
                size=(n_samples, vector_dim)
            )

            synthetic_vectors = adjust_statistics(
                base_vectors,
                target_mean=row['overall_mean'],
                target_std=row['overall_std'],
                target_skew=row['asymmetry_avg'],
                target_kurt=row['excess_avg']
            )

        entries = []
        for vector in synthetic_vectors:
            entry = ""
            for i in range(MAX_TOKENS_PER_ENTRY):
                vectorised_token = vector[i * VECTOR_SIZE:(i + 1) * VECTOR_SIZE]
                most_similar_words = model.wv.similar_by_vector(vectorised_token, topn=5)
                # print(most_similar_words)
                for word, _ in most_similar_words:
                    if str(word).isalnum():
                        entry += f" {word}"
            entries.append(entry.strip())

        synthetic_data.append({
            'column': row['column'],
            'vectors': synthetic_vectors,
            'entries': entries,
            'original_stats': row
        })

    return synthetic_data


def adjust_statistics(vectors, target_mean, target_std, target_skew, target_kurt):
    vectors = vectors - np.mean(vectors, axis=0)    # центрирование
    current_std = np.std(vectors, axis=0)   # маштаб
    vectors = vectors * (target_std / (current_std + 1e-8))
    vectors = vectors + target_mean     # сдвиг

    return vectors

In [9]:
def validate_synthetic_data(synthetic_data):
    validation_results = []

    for data in synthetic_data:
        vectors = data['vectors']
        entries = data['entries']
        vectorised_entries = get_vectorised_entries(entries)
        original_stats = data['original_stats']

        synth_mean = np.mean(vectorised_entries, axis=0)
        synth_std = np.std(vectorised_entries, axis=0)
        synth_skew = stats.skew(vectorised_entries, axis=0)
        synth_kurt = stats.kurtosis(vectorised_entries, axis=0)

        validation_results.append({
            'column': original_stats['column'],
            'original_mean': original_stats['overall_mean'],
            'synthetic_mean': np.mean(synth_mean),
            'mean_error': np.abs(np.mean(synth_mean) - original_stats['overall_mean']),

            'original_std': original_stats['overall_std'],
            'synthetic_std': np.mean(synth_std),
            'std_error': np.abs(np.mean(synth_std) - original_stats['overall_std']),

            'original_skew': original_stats['asymmetry_avg'],
            'synthetic_skew': np.mean(synth_skew),
            'skew_error': np.abs(np.mean(synth_skew) - original_stats['asymmetry_avg']),

            'original_kurt': original_stats['excess_avg'],
            'synthetic_kurt': np.mean(synth_kurt),
            'kurt_error': np.abs(np.mean(synth_kurt) - original_stats['excess_avg']),

            'n_samples': len(vectorised_entries),
            'vector_dim': vectorised_entries.shape[1]
        })

    return pd.DataFrame(validation_results)

In [13]:
methods = ['statistical_adjustment']
results = {}

for method in methods:
    print(f"{method}")
    synthetic_data = generate_synthetic_vectors(stats_df, method=method)
    # print(synthetic_data[0]['entries'])
    validation_df = validate_synthetic_data(synthetic_data)


    results[method] = {
        'data': synthetic_data,
        'validation': validation_df
    }
    # print(validation_df[['column', 'mean_error', 'std_error', 'skew_error', 'kurt_error']])
    print(validation_df[['column', 'original_mean', 'synthetic_mean', 'mean_error', 'original_std', 'synthetic_std', 'std_error', 'original_skew', 'synthetic_skew', 'skew_error', 'original_kurt', 'synthetic_kurt', 'kurt_error']])

statistical_adjustment
0
1
       column  original_mean  synthetic_mean  mean_error  original_std  \
0     article      -0.034556       -0.019673    0.014883      0.191570
1  highlights      -0.032811       -0.019739    0.013072      0.198002

   synthetic_std  std_error  original_skew  synthetic_skew  skew_error  \
0       0.026402   0.165168      -0.061589       -0.006551    0.055039
1       0.026788   0.171215      -0.068840       -0.003062    0.065778

   original_kurt  synthetic_kurt  kurt_error
0      -0.273300        0.052763    0.326063
1      -0.161357        0.024697    0.186053

In [15]:
synthetic_data[0]["entries"]

['2 W No blaze 40 13 Mt SES blaze 2 24 48 SES 5 2 Mt HIV 13 40 40 As Up Mt 13 80 Mt 26 2 18 Mt 23 W 40 No 5 1 2 Mt 26 Mt HIV Up 15 12 5 Mt Bonn On 5 13 150 23 If Mt Up 23 18 26 Mt 2 run If ANZ 2 No 5 13 2 23 W Mt 13 26 48 As 40 23 80 As 25 2 40 13 26 If 2 SES 5 HIV W 5 Mt 13 Bonn 40 W 26 13 14 5 Mt 2 24 oil Mt 13 UN 40 5 SES 15 5 80 2 W As UN No 13 Mt SES 23 13 5 If 23 80 18 Mt 26 Mt Up SES 23 AFP 23 5 15 1 Mt 15 13 Mt W 40 5 HIV 13 80',
 '5 48 23 No Up 40 25 1 If 5 1 26 SES Mt 5 26 2 AFP 21 Up W SES AFP 150 1 As 24 Mt 2 5 15 13 On SES 5 HIV Mt 13 26 Mt 23 1 On 2 5 13 150 run ANZ 26 Mt 1 Mt 23 HIV W 2 40 2 5 13 W 13 Mt 23 18 40 13 5 Up 23 12 2 13 18 Up 150 2 15 Mt 24 80 40 1 As No 14 5 Mt 26 14 5 If 80 drug W Mt If 40 2 80 On If As W As 25 18 23 5 2 80 26 40 Up 5 blaze ANZ 2 5 W drug Kabul 5 13 80 At If 2 As Mt UN 5 AFP blaze 40 80 5 40 Mt On No Mt 40 SES 48 AFP 5 2 40 UN 18',
 'Mt Up 23 25 150 5 40 W 26 13 5 Mt 2 15 1 Mt 150 AFP 2 Mt SES 15 40 AFP 15 40 AFP Nauru As 2 Mt Up blaze 40 15 2 80 24 13 Mt 40 2 5 SES Mt 40 15 23 48 5 Mt W As On 5 15 26 Mt 48 Mt 15 2 AFP 13 Mt 13 23 40 As 5 40 14 Up 18 5 13 Mt 48 150 2 ANZ 15 No 40 5 23 Bonn oil 5 2 13 Mt 2 23 21 No 150 HIV As 40 80 my Mt Up No 14 13 14 18 2 Up 80 40 SES W 2 14 oil 24 2002 23 SES Up 24 48 Mt 26 5 Fatah 14 2 24 No UN 18 15 13 1 40 2 5 2 HIV 15 AFP 2 Mt 26 Up 18 5 40 SES 1 W',
 '48 13 40 15 SES 23 13 14 25 26 40 1 W As 26 2 80 No 23 W Mt Up 1 oil 15 5 40 21 UN Assa 40 Up SES 5 As Mt 5 13 As Mt W On 12 26 25 Mt swept Up 150 W 40 SES No 48 Mt 13 2 SES 5 40 48 23 drug SES W 5 Ms 25 13 48 23 15 my blaze 23 If pilot 80 21 25 26 23 HIV W 40 12 At 5 HIV 48 As SES 40 AFP 80 As 1 Mt Up 15 12 5 13 14 drug blaze As 5 150 20 5 48 Ms 14 blaze Mt 13 ANZ Dr 21 2 As drug 5 13 40 48 25 As 1 HIV Up 48 24 40 48 Mt 20 AFP ANZ 15 25 Up 20 5 Mt 150 40 13 2 Up Mt W',
 'UN 12 Up Mt 2 25 5 15 ANZ 1 26 Mt Up 23 Mt W Up 26 1 Mt 5 2 blaze 21 23 1 26 drug 25 15 drug 80 No 40 25 23 No 13 5 25 80 18 5 Up Mt SES HIV 2 26 Up 1 As 13 5 Mt SES Mt HIV Up 15 12 Mt 80 2 26 Mt 5 Up 26 24 Mt 26 15 ANZ SES 5 23 Mt SES Ms 13 As 14 Mt 40 13 W 150 21 5 40 AFP 13 80 Mt 23 5 21 13 40 SES 13 Up No Mt W 40 13 AFP Up As 1 26 40 Mt 5 150 21 Dr Mt W 25 HIV 15 Mt 15 HIV 23 5 1 2 26 ANZ 2 5 Mt 13 Up 1 2 25 As Up 5 Up 150 drug W 1 40 Up 15 5',
 '40 2 150 No Up 23 5 oil Mt 48 5 40 13 14 15 5 Mt 40 AFP 1 2 ANZ As 25 blaze 5 Mt SES 48 AFP Mt 40 14 Up UN Mt 40 23 UN 2 Mt Up 2 13 2 5 40 Mt Up 23 Mt 15 18 Sarah 2 Mt 40 13 15 5 40 SES As 14 40 Mt 5 13 SES ANZ Mt Up 14 Kabul Up Mt SES Mt 13 5 Up Up If 2 18 Lee Mt 18 15 Up 13 15 48 HIV oil 25 2 1 5 Mt 26 5 40 26 1 150 Mt 15 SES oil HIV Mt 40 drug If 25 48 HIV 2 Up blaze 5 40 2 Mt 15 2 20 15 25 If 40 1 As 5 12 40 HIV 5 No 13 2 40 HIH drug 2 23 1 80 40 Up UN Mt An',
 '5 14 40 HIV SES Mt 5 SES 13 15 15 HIV AFP 150 On Mt 2 80 blaze ethnic Up Mt 2 blaze 1 Mt 13 Up 150 40 13 W 25 HIV 15 2 Mt 15 AFP 13 80 If Europe Doug 2 23 25 UN ANZ 80 26 23 Up 23 Mt 40 UN Mt 14 48 15 AFP 5 Mt AFP 15 2 1 23 25 UN 15 HIV As Mt 40 AFP Mt 14 As W 21 Mt 25 23 W Mt SES 48 23 15 5 80 HIV W 48 1 40 15 AFP 26 13 15 Mt 26 23 2 Ms SES If drug Mt AFP 15 ANZ 48 1 AFP W 25 No drug 20 HIH 5 15 ANZ UN At 40 23 13 SES W Mt SES 40 5 1 Up 1 SES 5 5 Up Mt 24 If 5 W SES 13',
 '40 SES W If 18 5 2 Up 150 W 13 2 80 18 2 Mt 40 W UN 5 24 2 ANZ oil 40 2 Mt Up 24 5 SES Ms W Mt 2 Up W AFP blaze 80 blaze 23 W 25 W As UN SES 2 40 HIH data 23 5 13 Mt 40 Mt 1 AFP blaze Mt 15 23 13 48 Mt W 26 Up 5 13 26 150 25 5 W Kabul 40 80 Up blaze No 5 80 14 If drug 13 As 24 At Assa 5 Mt HIV drug 48 40 80 15 AFP On SES 40 48 23 HIV Mt 13 ANZ 5 2 5 Mt 40 48 2 1 80 26 40 AFP 5 Mt 15 21 HIV Mt 26 15 Up SES 5 26 AFP drug 14 5 40 As 13 AFP Up Mt 24 5 18 2 Mt SES 15 26',
 '48 14 HIV Sarah Mt 5 24 1 15 1 15 SES 40 5 5 blaze 25 Up 2 40 SES drug Ms 5 13 80 SES 48 Mt 23 As 13 25 5 HIV 48 14 AFP 5 W SES 14 Mt Up 18 SES 21 48 18 Ms 23 W 15 2 26 1 No 23 40 Mt 2 25 5 25 48 150 Mt 5 2 Mt UN 24 5 23 Mt oil 18 5 Mt 40 15 On 5 13 150 2 5 80 26 150 5 40 As 26 AFP 5 40 1 2 26 25 23 blaze HIV 1 23 ANZ Blue blaze Mt 5 15 AFP 2 Mt 15 13 AFP 40 AFP 2 13 80 40 13 As 2 W 2 40 Mt AFP 15 W Mt 18 blaze Mt 15 Up AFP 40 Up Mt 80 26 15 40 SES 2 1 15',
 '5 23 15 2 ANZ Mt 23 15 Up 40 2 No 80 As SES 15 drug Mt 5 40 As SES 23 No 5 Mt ANZ Dr 25 Mt W Up 2 24 HIV 150 drug 14 15 Mt 5 Up 40 HIV 5 80 W 40 2 5 Mt UN 25 40 5 80 40 1 AFP Mt 5 2 AFP ANZ Mt 5 2 21 On 23 Up 25 If 40 1 25 Mt 15 40 2 AFP 15 26 blaze 2 Up 26 Mt ANZ 5 W As 13 23 5 40 1 25 23 18 SES 20 Up 23 AFP Ms 2002 2 Mt 80 No UN As 80 10 40 5 If drug 25 26 AFP 25 W 5 1 2 80 Fatah 5 No 150 blaze UN 5 Mt 20 oil If 2 40 23 If No 5 UN W blaze 2 5 18 25 blaze Sarah',
 '5 40 Mt AFP W As 40 2 14 blaze 5 1 26 Up 2 Mt 18 23 Up 2 1 W ANZ As Mt 13 As 26 2 AFP 25 1 SES 5 14 Ms drug 26 80 15 AFP SES 26 1 Mt 2 40 No As 1 Mt 13 15 2 5 5 24 Up As 40 HIV 80 18 blaze 14 13 Mt 12 HIV 2 40 25 drug 150 5 25 26 Mt 5 13 48 15 23 Mt On ANZ Ms Mt 2 Ms 48 blaze 2 SES Up HIV No Mt 24 25 W 2 40 2 Up If Mt 13 Up 2 SES Up SES Mt If 1999 13 2 Mt W 21 2 5 13 48 W 23 5 1 Up If 15 HIV W 80 48 5 23 If Fatah 40 2 AFP drug 21 2 Mt 13 ANZ 11',
 'Mt 26 40 Up 5 Mt 26 SES blaze 21 5 Mt 13 26 23 13 Mt SES 23 48 2 150 UN 13 26 5 13 W 2 18 5 48 13 AFP HIV Mt 13 2 23 21 5 15 Mt 150 HIV 5 48 Mt 25 40 5 2 UN Bonn Mt 15 2 AFP HIV Mt Up 25 15 Mt 15 W 40 As Mt Ms 48 As drug 2 80 Mt 26 20 40 18 2 150 No 13 2 Mt 40 21 Mt 2 Up 24 As 80 25 24 ANZ Mt 13 40 As If 40 5 As Up UN 5 W Mt SES Ms Mt 25 15 Up Mt 2 15 SES AFP Mt 2 150 blaze 5 1 Mt 26 21 1 80 15 26 14 2 40 13 As 80 Up 26 5 HIV 24 5 23 13 Mt 40 Mt 2 24 blaze 15',
 '2 5 Mt 24 15 5 2 48 As W 15 5 SES AFP 2 Mt 23 W SES 2 13 15 At 24 2 15 40 Mt 21 W 5 23 26 Mt 5 Mt 23 Fatah 150 23 W 26 80 No 40 Up 1 UN 23 13 5 Mt 150 Mt 2 18 As 13 2 13 Up AFP 150 Mt 5 26 13 1 40 UN 24 If 23 Mt 40 18 2 Mt 40 AFP Mt AFP UN ANZ Bonn 2 W 5 SES HIV Mt 14 SES HIV 48 5 2 23 Up ANZ drug SES HIV 15 48 5 Up 2 1 SES 2 14 Up blaze Mt As 23 13 W 5 Up 48 If 80 1 SES Up UN 5 48 14 drug 13 5 Mt 13 Fatah 5 13 40 12 As 5 26 13 Mt 23 2 Mt 13 40 W',
 '13 48 Mt At 5 oil 2 drug Nauru 23 HIV 48 Mt 5 26 40 1 40 23 SES 5 HIV 80 20 HIV SES W Mt 40 25 150 40 SES As Up 15 80 1 On UN 26 Mt AFP 2 48 Ms 23 150 No UN 2 13 40 80 18 Mt 13 40 If W 23 SES 15 25 At 5 13 23 14 SES 1 2 As 40 On 5 23 As 150 25 1 26 ANZ 80 2 15 40 On 5 5 Mt 14 48 Ms Mt 12 Sarah AFP 14 23 Mt 80 15 25 2 5 15 13 SES 40 2 W SES As 2 5 1 15 Mt 5 20 48 oil As 40 1 If drug 2 1 5 As 48 Mt As W 150 2 SES Mt 40 No Mt 24 40 At oil 15 Mt HIV 80 23',
 '2 Mt 48 SES 5 5 2 HIV Mt SES SES Up 26 1 W Mt 14 2 blaze 48 40 13 80 UN Mt 15 26 2 AFP HIV W 48 SES 2 80 AFP 40 ANZ 5 23 Mt 24 Mt As 14 48 23 13 2 Up As Mt 5 Mt 21 11 W 5 Mt On 12 Mt 24 21 Up 15 Mt 5 40 2 AFP 40 2 ANZ AFP 15 80 2 5 W 5 80 26 AFP 5 80 W 25 HIV 2 As 150 Team HIH 5 SES 13 drug Two Up If 5 20 48 5 80 2 On HIV 5 23 13 Mt Fatah 5 13 2 SES 26 5 Mt If Up HIV 40 W SES Mt 1 Mt HIV 40 13 5 5 23 No 11 20 1 5 80 UN Mt 15 HIV SES blaze 5 25 my 150 48',
 'Mt 2 40 150 13 5 40 SES 25 On 80 5 SES W AFP 13 23 W 5 As Mt 5 No 48 5 HIV Up 24 SES W 1 Ms 20 2 80 40 24 If If SES 80 23 W 24 26 11 5 Mt W 25 13 Mt 80 15 23 W 26 Mt 1 23 Mt 5 14 26 13 ANZ 80 blaze 2 On 26 As 23 48 14 As HIV 12 15 2 5 HIV 80 21 AFP 2 Mt 13 150 18 Mt W 2 Up No 2 150 AFP Mt On 5 Mt 48 AFP 2 Mt 5 25 1 2 1 SES 40 14 drug 5 23 80 24 48 13 Up Mt As SES 23 40 150 Mt 5 25 23 150 18 13 UN 40 As HIV Mt 23 15 80 25 HIH AFP 48 20 5 SES HIV 48 1',
 '15 1 Up SES Mt 40 Mt 13 If 1 2 13 5 15 If 5 1 40 2 Mt 23 15 AFP SES 5 HIV 25 13 15 Mt 2 40 blaze 80 As 40 SES 1 14 Mt 1 40 2 AFP Mt 15 Up UN 14 5 Mt 26 15 14 AFP 15 Mt drug 5 13 drug 2 UN 13 SES Karzai As keep 13 40 HIV As 14 15 48 Mt 18 24 Mt 23 1 SES 15 5 Mt 40 1 15 40 HIV Mt 5 W Mt 26 80 15 23 Mt 23 15 25 W Up 23 14 26 W Mt 23 12 Up Mt 21 blaze gun 2 SES 14 Mt As Up 24 5 Mt 48 2 Mt 13 21 11 Mt 13 20 21 23 13 W 40 2 40 W 13 As 5 Mt 24 2 Mt W SES As Ms',
 '40 13 5 ANZ 1 13 2 24 80 23 W As Up swept 5 W SES 40 80 Mt 2 Up blaze Mt Up SES W 13 As Mt W drug 1 Up drug SES 26 1 80 26 23 18 Mt 15 48 80 25 Mt 150 blaze W Up 5 Mt HIV 150 23 1 20 21 26 SES Up Kabul 40 1 80 24 Up 40 1 As W UN 23 48 2 25 Mt 25 40 23 W 15 AFP 40 As 1 Mt 2 15 SES 20 W 26 2 80 23 Mt ANZ blaze On Up 5 2 Mt SES 23 5 Mt 150 11 UN 23 18 Ms 21 13 Up SES 15 5 40 Mt 26 80 Up 40 48 21 Mt 15 5 Mt 26 24 Mt 15 25 SES 2 Mt 48 HIV 15 24 5 2 If 13 drug',
 '40 5 No 48 2 5 40 Mt Up Mt 5 Up 13 25 5 AFP 15 2 48 5 Mt 23 Up 48 5 Mt 14 13 W 5 15 24 Mt ANZ Mt 5 Up 23 15 23 80 13 18 1 Ms As Up my embassy Mt 5 48 25 40 As 13 80 my 80 23 26 1 No 5 Mt 48 150 15 5 48 40 On 5 80 Mt 15 48 Up Mt 13 5 23 drug HIV 21 5 Mt blaze Up 48 W 15 40 14 drug 5 Mt 2 Up 14 23 blaze SES 48 80 40 As 1 drug SES 5 Up Mt 150 W 18 SES As If Mt 26 20 13 15 2 26 AFP SES Ms Mt HIV 15 Up 5 Mt 40 14 SES 1 40 If 13 HIV SES 14 Mt 25 40 Up AFP SES HIV',
 'Mt 5 HIV 14 21 5 Mt If SES On Mt AFP 5 Ms 15 23 Mt 1 15 ANZ Mt 1 As Up 15 5 2 Mt 13 Mt 48 20 HIV gun Mt 5 13 40 21 2 Mt 13 23 18 1 13 2 SES HIV 5 48 40 14 W 13 23 Up 15 Mt 23 26 Up 18 5 24 AFP Up blaze 5 AFP blaze 2 drug 5 40 AFP 14 HIV 1 W drug As SES Mt 1 26 SES 23 2 SES 23 Up 18 5 Mt 21 40 HIV 5 SES 13 1 26 Mt W 5 SES 23 13 40 5 SES 1 2 Mt 23 80 W 2 80 24 As 15 5 13 HIV Mt 15 HIV AFP 2 40 2 25 1 15 5 1 40 24 drug 2 Mt 13 150 UN 23 13 80 18 W HIV 13 5 W',
 '13 40 As 2 80 13 80 UN 1 2 W On 24 No 5 23 Up If W Mt 5 25 blaze Lee 5 40 Mt drug 80 25 Mt 23 drug W 40 Ms ANZ 48 2 80 HIV 5 2 Mt 1 26 1 80 21 23 2 Mt W SES gun 18 If Up Sarah As 2 13 14 25 5 Mt 48 150 25 Mt HIV 13 2 At SES As 13 UN 23 15 25 Up 2 Up 1 ANZ UN 5 Mt HIV 14 5 Mt 23 26 15 2 AFP 13 Mt 48 40 2 13 150 AFP 5 40 1 SES HIV 5 HIV 21 drug 15 23 Mt 15 AFP 150 Mt 13 26 80 5 13 1 18 Mt As W 1 23 5 If 13 2 13 26 As HIV 25 80 HIV If swept',
 '13 Mt AFP 80 Up 40 13 2 18 2 13 5 Mt ANZ Up 25 13 14 Mt 2 As 1 SES 5 Mt 40 AFP 26 2 1 As 23 AFP 1 Mt 25 Up Mt 2 23 SES W 23 48 26 Mt HIV 14 SES Up 1 80 48 5 HIV 24 SES 2 13 W Up 15 As W SES 1 5 Mt AFP 1 21 2 40 150 15 ANZ 40 80 48 embassy Mt Up W 26 21 2 blaze 25 On HIV Up 23 Ms W AFP 48 HIV Mt 15 AFP 5 21 40 2001 Ms 2 1 UN No 13 Mt 2 W 15 150 SES Up Mt 40 13 48 40 23 W Fatah Mt 23 5 13 Up 5 Mt Up 2 13 40 Mt If 23 48 AFP 15 Mt 5 2 SES 15 ANZ Mt 15 24 25 HIV',
 'SES Mt W 150 Up 15 Mt HIV 1 40 5 Mt 23 21 14 Mt 40 13 15 25 5 13 14 48 26 5 AFP Up 26 As W 40 23 As 80 40 2 Up 80 W Up 150 No 48 Mt Up W ASIO At HIV 14 23 48 5 HIV SES 13 40 80 26 HIV 48 2 W 13 UN 5 1 Mt 23 13 1 Mt 26 AFP 15 13 23 1 Mt 40 1 AFP As 40 No HIV 1 ANZ HIH 5 23 If 12 13 14 Mt 40 HIV SES 5 14 W HIV 13 2 14 Mt ANZ 5 40 Up SES 21 Mt As SES 50 2 13 18 W 2 13 As 14 At HIV 1 As 23 25 23 13 40 14 25 SES 5 W AFP Up Mt 23 14 Up As Mt 26 SES 48 Up',
 '40 13 25 W If 5 40 14 150 drug 13 40 As 15 2 W AFP UN 1 40 AFP As 1 SES 1 40 23 No Mt HIV 5 150 26 Mt 40 W As AFP 23 15 Mt 2 Up 2 ANZ SES 25 Up 5 On 13 2 2 40 SES Up If 13 blaze 48 Up HIV Up 5 No 23 5 48 HIV Mt Up Mt SES 5 2 Up 40 blaze If AFP gun 5 blaze 1 25 13 Mt 2 21 26 23 Mt 80 25 48 40 5 13 SES 150 Mt 24 Up 48 18 40 25 15 AFP SES 15 Mt 26 ANZ 5 13 14 21 150 Mt 23 Up If 150 Mt 15 Up 24 12 2 Up 13 SES 5 Mt 21 my Mt 13 40 Nauru 5 HIV 15 Bonn 5 2 13 drug Fatah',
 'As Up AFP No 5 Mt 48 W Up 23 Mt If 1 Mt If drug Fatah 23 Mt W SES ANZ 23 80 Mt 23 48 15 40 Mt SES 13 As 1 15 AFP drug Mt HIV Up 150 No 23 Mt 5 1 UN 24 26 Mt Up 48 5 Mt 26 150 AFP 5 40 24 SES 13 23 13 14 25 21 SES 40 15 gun 80 13 2 If 1 26 SES 13 40 1 Up 40 No 150 23 my Mt 5 15 Up 13 AFP 5 Mt 2 Mt 2 13 1 As Mt 15 W 24 2 2 Mt 80 40 Ms 80 25 14 18 5 Mt 13 1 150 48 40 13 No 14 2 Mt As 5 14 UN As 24 25 Up Mt 150 25 Up 23 2 W As 18 Assa HIV 48 80 blaze W 5 Up 26 HIV',
 '40 As SES Up 15 80 SES 11 blaze Up 40 HIV No Up Nauru 5 24 oil 26 Nauru 14 5 If Up 40 23 No 20 25 Mt 23 Up Ms UN 2 2 Mt Up No 26 W 18 1 Ms 2 Mt 15 SES As oil 2 HIV 15 Mt 40 13 SES Assa 5 1 40 Mt 14 5 ANZ 15 25 Sir 5 Mt 15 13 Bonn 15 24 Up AFP 14 UN As 2 21 blaze 5 HIV 1 14 As 5 2 40 13 No 40 2 UN 23 No Up HIV 23 SES 11 5 40 13 W As 13 HIV 48 14 15 HIV Mt Up 26 W Mt 40 48 80 15 5 2 Mt HIV 40 2 40 Mt SES 5 5 40 13 1 14 Mt 15 AFP 25 18 40 150 23 Up 15 5 As 40 13 2 5 80 Mt HIV 21',
 'Mt SES 25 No 48 23 Mt Up 15 40 5 Up HIV 13 Mt 1 40 2 80 Mt 5 SES W 2 No Mt 23 W 150 25 Mt 5 40 As SES 80 24 48 run 14 2 1 UN 40 SES Mt As 40 15 13 13 15 14 SES HIV Mt 2 40 1 As 2 Up 1 24 UN Up 23 14 SES 25 48 W AFP Up HIV 5 13 blaze 23 Mt 40 W 25 80 24 Mt On 25 Assa 21 5 Mt 23 W 48 Up 24 Mt 13 18 40 23 5 80 HIV 5 SES 14 25 48 Mt 40 2 SES W HIV 15 26 SES 5 5 2 13 W 48 Mt W 2 80 48 80 UN 24 5 Up 26 W Mt 1 No 5 As Mt 15 80 ANZ At Mt 13 As SES 40 2 Up 5 UN',
 'AFP 40 Mt drug As Mt 25 2 SES 12 Mt As 12 On HIV 2 1 W 18 Up 5 15 80 26 AFP 15 5 80 23 drug If 15 Mt 80 13 40 5 Mt 1 2 40 ANZ 13 Bonn Mt 15 40 1 24 40 13 SES If W SES 40 HIV 2 1 23 Mt 5 26 2 5 SES drug 40 Up As 13 HIV 23 26 Up 2 13 40 SES 15 5 23 W Mt If 13 As W drug HIV 23 15 48 25 2 5 1 Assa AFP 2 23 UN 40 ANZ 5 80 48 15 11 Mt 5 15 oil Nauru AFP 1 14 Blue Nauru 5 Up 15 If 25 SES 2 13 40 Ms 5 1 23 40 No 13 As HIH W my 5 48 As 40 150 24 HIV Mt AFP 40 2 As 40 If',
 '40 As HIV 2 Up 5 If AFP drug Neil 15 25 Mt 18 ANZ SES 23 40 5 13 26 5 W HIV 21 2 Up HIV 1 SES W No HIV 48 1 40 As 5 25 5 Mt 21 UN 23 Mt 26 W 23 SES W 23 24 12 5 2 18 Ms 26 HIV 5 13 Up 40 HIV 1 If 12 Mt 40 11 As 2 2 Up 40 HIH 48 5 As W drug 40 HIV 14 As 5 2 W As SES 13 1 40 26 Up If 40 Mt As 15 oil 13 5 Mt 40 14 5 2 Mt HIV 13 23 13 18 2 No 13 2 18 1 W 5 13 SES Mt 14 15 HIV 1 SES AFP Mt 25 21 ANZ 5 48 13 150 AFP W Mt 13 Two 5 13 26 20 W 80 2 No As 24',
 '5 25 150 HIV W 13 2 25 150 drug 2 W UN 26 40 13 Up HIV 18 2 5 13 If ANZ 5 15 HIV 48 40 W SES 13 18 80 W 15 AFP 13 40 150 SES No Up Mt Up 26 2 AFP 150 2 5 15 40 Mt 5 W 23 26 Mt 5 40 As 2 SES 23 drug AFP As Mt Up As 23 15 SES 1 As 26 1 40 2 Up blaze 80 2 24 14 13 23 W 13 As 80 2 UN 13 As 18 Mt 2 80 On 12 40 13 drug gun Mt 48 SES 26 25 2 As 40 AFP 150 Mt 23 13 SES SES No 2 W 13 Mt 23 25 18 Up 2 18 15 blaze ANZ 1 At SES blaze As 5 40 13 1 14 W 80 40 5 18 48 drug W If HIV',
 '1 2 15 UN Mt 2 80 UN 23 drug Mt 48 15 13 2 5 Mt 15 21 150 5 80 1 40 26 5 48 15 Up SES 5 Mt 13 SES 18 5 13 15 26 2 5 Mt 26 W 5 Up Mt 40 5 48 2 80 ANZ 23 5 Mt 13 18 23 Mt On W 12 As AFP Up W drug 5 Mt 25 15 Sarah HIV 40 48 26 2 13 21 oil 150 2 SES 23 15 HIV 5 48 SES 24 If SES W 13 Mt 26 UN 1 80 Mt 2 21 Up 15 Mt 40 2002 SES As Mt 26 1 Up 5 14 26 Up Ms Mt W SES 25 23 2 23 15 Mt 18 Mt SES ANZ AFP 25 Mt 40 23 15 HIV 26 5 48 150 W Mt 5 W 150 Up SES W 25 AFP Mt',
 '5 23 15 2 1 Mt SES AFP Up 2 As 13 80 Mt 15 21 AFP HIV HIV swept At 13 Blue 23 ANZ AFP 80 5 W Mt No 40 48 5 12 2001 23 Mt 18 2 21 23 Mt As 150 15 1 26 2 SES UN 48 25 2 Up AFP 2 UN 5 23 5 48 HIV No 2 SES Mt ANZ 13 2 13 SES Mt W 13 23 40 5 48 5 2 14 No 48 13 48 40 Mt 23 5 Up 13 40 Up 24 2001 blaze Mt W Mt 13 As No Mt 40 26 15 AFP Mt 5 15 HIV 48 5 Mt 24 14 blaze 23 25 80 W blaze SES 1 40 W Mt As 48 No 13 40 5 On blaze 48 15 25 48 23 AFP 2 Up Mt 18 SES HIV 13 Mt 5 14',
 '2 As SES Kabul 15 Mt 23 40 As 13 2 HIV Mt 25 Mt 40 13 HIV W Mt 40 Up W As 23 18 13 W 25 5 13 48 14 40 SES 25 15 1 2 HIV 23 14 blaze HIV 25 24 80 14 2 23 20 Up 15 Mt 5 15 1 Up 2 15 UN 80 AFP 80 13 Mt 40 If 2 my 15 26 23 As 2 40 15 13 5 W Mt blaze 13 15 ANZ Up Mt 1 5 2 1 UN As 5 Mt 48 13 40 W 5 13 14 15 12 20 AFP Up 2 As 48 my UN 2 Mt AFP On As Up 2 blaze If 23 Mt 5 40 13 5 13 15 20 25 23 2 As 11 W Mt 23 2 26 Up 13 Mt As SES 18 23 If Up blaze 80 Mt W 23 13 1',
 'Mt 40 21 No 2 80 23 W 40 SES SES 2 25 W HIV 40 5 21 18 SES 2 SES 26 18 5 Mt 25 23 5 AFP 40 Mt SES 40 23 13 Mt 5 Mt 23 40 5 13 5 Mt 14 21 Ms 13 80 2 15 25 ANZ blaze As 40 Up 2 13 40 40 Up Mt SES W Mt 5 1 2 AFP Up Mt 23 2 Up Mt ANZ No 5 150 At drug HIV Mt 150 21 5 On At 26 blaze Mt 11 No At 14 5 15 SES 13 5 Mt 1 HIV 40 15 26 150 As AFP Up 1 5 23 15 Mt 80 13 26 AFP 2 23 18 If 13 5 40 150 14 Up 2 13 5 As 14 5 2 80 24 AFP 5 1 26 150 Mt 2 1 SES As 26',
 '5 14 Mt 12 5 2 24 25 80 5 150 25 my As 80 48 Mt W 5 AFP Mt 80 Mt 2 AFP 15 Fatah 5 Mt 26 SES AFP 48 24 40 80 HIV AFP 2 80 HIV 48 5 Mt 13 26 As 2 5 150 UN Sarah Mt 23 No Up 40 2 SES Ms 40 W Mt 23 40 21 2 5 24 Ms 48 Bonn 5 Mt 40 13 150 40 5 14 W HIV 40 HIV Mt Up 18 If 5 25 40 1 2 Up UN 26 13 Mt ANZ embassy 5 2 SES Up W 5 1 2 24 Mt 23 80 HIV 15 13 Mt 1 23 12 Mt Up 14 As 13 If Mt 21 40 23 26 Up AFP 23 No 2 Mt 13 15 20 5 24 Up Mt 40 As AFP Mt 1 2 Mt 13 If',
 '5 25 W my As 80 15 Mt 24 5 AFP 48 14 15 5 Up drug 14 As 2 1 26 24 15 2 40 my W Ms Up 40 ANZ 1 drug 23 Mt HIV 80 25 40 2 80 ANZ 13 2 23 18 blaze ANZ 5 40 If SES 14 80 W 1 Mt 25 2 40 Mt SES 18 80 AFP 2 blaze 20 Up 2 Mt 150 blaze 2 13 Mt As 48 Ms HIV 25 blaze Mt 5 40 She 26 1 21 5 AFP Up 150 drug 14 As 13 23 80 ANZ 2 13 5 15 40 150 13 20 Assa gun Mt 1 2 15 23 Mt 13 40 80 Sarah 23 Mt blaze 25 18 Mt 5 13 48 W Mt 2 ANZ W 18 Mt 2 15 1 AFP Mt 15 23 5 1 5 25 Up 23 150 40 If 2 13 Mt',
 '5 40 1 24 On 15 Mt 13 20 1 Mt 5 26 As Up 2 SES W 40 As 13 12 25 Mt AFP 14 2002 15 1 No 40 As 5 13 48 Mt 5 Mt 13 14 15 Mt Ms 48 23 swept Mt 2 13 18 As Mt As 2 24 Sarah 5 13 1 As 14 2 On 5 SES blaze Mt 2 15 1 18 Mt 2 150 15 SES 25 14 150 23 80 5 26 21 12 18 2 Mt As 40 26 5 Mt 48 13 24 Mt 40 W SES Up 40 14 48 21 13 Mt 40 5 UN 13 As 40 Mt SES 5 Up Mt 15 24 150 Mt 25 80 Blue 23 2 15 No 48 Up Mt 5 HIV 15 Mt UN 2 Up 15 40 1 SES ANZ Up Mt 23 HIV 25 12 48 Up No AFP',
 '5 W 80 26 13 5 Mt 2 13 21 80 26 150 At run 40 Mt 5 SES 13 Mt 15 5 AFP 48 Mt 25 blaze 18 40 Mt 5 W As 1 1 23 W As 15 26 Mt 15 Up SES 23 15 18 40 SES 1 Up 15 23 14 SES Mt 13 14 40 HIV 40 Up No 15 5 40 SES HIV 15 5 SES 40 18 Mt 26 SES W AFP 2 As 5 1 UN W 2 13 40 2 Mt 15 1 Mt 5 26 SES 40 Mt SES 2 Up blaze Mt 13 Up 26 5 23 W HIV 26 5 Mt HIV On 21 2 13 HIV Up blaze 40 13 14 SES 48 13 Up Mt 23 1 Mt 5 13 W 24 5 40 SES W 2 Mt W As 13 24 2 Mt W 15 21',
 'Mt 13 5 W 21 Mt 15 2 5 1 Mt W 2 13 As 5 AFP 25 15 SES 13 5 23 W 48 5 Mt 1 24 5 23 If oil SES 5 13 23 48 Up 2 40 80 gun 5 Up W 40 SES 80 If 25 15 1 5 24 W 26 Mt 13 2 blaze Mt 13 15 5 W Mt 23 18 13 2 SES Up 13 26 5 80 24 48 blaze 14 2 13 As 24 48 13 2 15 As 18 5 80 Ms 40 5 13 ANZ Mt As 1 40 2 2 Up 26 Mt Mt 14 Up 13 W 25 15 40 As 40 15 No Mt 25 5 HIV 21 14 AFP 5 23 15 1 80 Mt W 26 13 2 48 HIV 13 W 150 5 2 Mt 13 40 5 Mt Up 2 14',
 '5 26 Mt 1 23 Mt 13 2 As 25 13 Mt 150 SES 50 80 Mt 23 1 UN 13 40 24 14 21 5 23 1 40 25 Mt 2 blaze HIV Mt 23 150 Up Fatah Mt 23 15 26 1 W Up 23 UN As 26 15 23 Assa 23 80 2 blaze Up If As 5 24 5 80 24 W 26 2 5 1 UN 40 As HIV 15 14 5 Mt 2 24 Mt 5 80 Up W 25 SES 80 2 Mt 15 24 26 Mt AFP 15 oil Fatah 5 13 14 150 Up gun Mt If 23 Mt 5 24 13 Mt 23 2 26 18 Mt 2 5 If 1 40 SES 13 26 SES UN Mt 23 80 2 15 48 ANZ 5 23 48 80 40 Mt 23 13 26 40 5 Ms Mt 24 20',
 '5 Mt 48 oil SES Mt 13 48 23 W 23 13 SES blaze 20 Mt 40 AFP 26 Up 48 24 5 As Up 5 48 14 HIV SES Mt 23 13 15 If Up 13 24 Karzai 48 HIV 15 1 ANZ 25 5 13 Mt blaze 40 Mt 13 Ms 48 40 5 Ms oil 23 Mt Mt 13 2 15 23 80 40 ANZ 2 W Up On As Karzai 5 2 48 Mt HIV 13 W Mt 48 AFP 1 5 21 blaze 15 5 Mt 21 blaze 14 13 W 26 SES No Mt Up 14 blaze As 40 Up 150 If 23 Mt Up 15 W Mt As 40 2 13 Mt 1 80 HIV SES HIV 5 W 2 SES W 48 AFP 21 48 40 5 5 1 As oil 5 Mt W drug 13 5 HIV No 48 5 2 UN 80',
 '25 blaze 5 Up SES HIV 25 blaze 2 15 25 1 No 48 Mt AFP 40 15 5 25 23 1 HIV 23 13 Mt 40 No 2 15 AFP 40 my Mt 5 2 15 40 2 13 23 15 1 5 48 25 HIV blaze 40 5 13 Mt SES 40 23 As 5 13 80 26 AFP 23 Up 21 W 2 150 25 Up Mt 15 25 AFP Mt 80 2 15 23 2 15 UN run 23 Mt 15 25 oil 5 1 25 80 15 23 Mt 18 At No Mt blaze 2 48 13 Mt 2 40 SES Mt 40 Up 25 SES 48 HIV AFP 80 Mt 5 2 15 13 2 5 SES 25 1 Mt W SES Up 48 26 1 AFP drug 80 2 80 blaze 26 5 25 14 ANZ drug 5 Mt 25 1 UN 5 80 HIV 15 AFP',
 '2 AFP 40 15 Mt 5 40 Mt 15 2 13 150 2 23 15 SES HIV 48 23 25 5 15 On 80 2 48 Up Ms SES 12 25 23 80 5 24 Mt 13 Up HIV HIV 14 13 2 24 2 SES 13 23 5 40 48 W 1 5 40 HIV Mt drug 26 23 1 HIV 23 Mt AFP SES 25 2 40 ANZ UN 24 23 13 W 2 18 Mt 23 SES 40 W Mt UN 24 HIV 40 blaze 25 my 14 Mt 25 15 As 1 26 1 40 80 W 5 26 15 1 2 40 Mt 26 HIV 15 Mt 5 23 48 drug 5 2 80 W 48 Mt 15 blaze Up 40 13 40 1 As SES 5 80 HIV 26 40 AFP 26 As 1 80 1 If 2 26 5 SES 1 2 As 5 13 SES Mt 1',

Per token encoding (32 tokens per entry, 1000 entries)
| col_id |column | mean_error | std_error | skew_error | kurt_error |
| :-- | :-- | --: | --: | --: | --: |
| 0 | article | 0.009493 | 0.070306 | 0.016213 | 0.224872 |
| 1 | highlights | 0.008788 | 0.074577 | 0.016814 | 0.025978 |

Per token encoding (32 tokens per entry, 10000 entries)
| col_id |column | mean_error | std_error | skew_error | kurt_error |
| :-- | :-- | --: | --: | --: | --: |
| 0 | article | 0.009477 | 0.071560 | 0.018867 | 0.097473 |
| 1 | highlights | 0.008795 | 0.074604 | 0.020299 | 0.057919 |

Per token encoding (128 tokens per entry, 1000 entries)
| col_id |column | mean_error | std_error | skew_error | kurt_error |
| :-- | :-- | --: | --: | --: | --: |
| 0 | article | 0.009570 | 0.080066 | 0.019298 | 0.402275 |
| 1 | highlights | 0.000851 | 0.054784 | 0.189310 | 62.405271 |

Per token encoding (256 tokens per entry, 1000 entries)
| col_id |column | mean_error | std_error | skew_error | kurt_error |
| :-- | :-- | --: | --: | --: | --: |
| 0 | article | 0.009448 | 0.083083 | 0.016279 | 0.337313 |
| 1 | highlights | 0.001706 | 0.030596 | 0.560300 | 333.181639 |

In [ ]:
synthetic_data

[{'column': 'article',
  'vectors': array([[-0.02918556, -0.00241555, -0.01755176, ..., -0.01850015,
          -0.02370537, -0.02502471],
         [-0.02091651, -0.0143409 , -0.02476307, ..., -0.01849512,
          -0.01591163, -0.0140214 ],
         [-0.01054276, -0.01340535, -0.01422865, ..., -0.01673924,
          -0.00102861, -0.02292433],
         ...,
         [-0.0035998 , -0.01470775, -0.01273879, ..., -0.01729498,
          -0.02569834, -0.00997742],
         [-0.00747992, -0.01899989, -0.00887265, ..., -0.0187878 ,
          -0.00836075, -0.01032919],
         [-0.01510822, -0.02989641, -0.01921276, ..., -0.01451408,
          -0.02706147, -0.0189524 ]]),
  'original_stats': column              article
  overall_mean      -0.016539
  overall_std         0.00661
  std_of_means       0.203823
  mean_of_medians   -0.016595
  asymmetry_avg      0.034912
  excess_avg         4.487738
  n_entries             11490
  vector_dim              300
  Name: 0, dtype: object},
 {'column': 'highlights',
  'vectors': array([[-1.32600255e-02, -7.99718218e-03, -9.88262412e-03, ...,
           2.60763541e-03, -2.47036315e-02,  1.64550911e-03],
         [ 9.74653068e-03, -2.23572419e-02, -3.08690159e-02, ...,
          -2.78733947e-02, -1.68197634e-02,  4.30552681e-03],
         [-5.70942604e-02, -1.58702561e-02, -1.44796333e-02, ...,
          -9.01138651e-03, -6.51539359e-05, -4.79207140e-03],
         ...,
         [-2.01515627e-02,  8.47863901e-03, -3.46542411e-03, ...,
           1.77655543e-03,  5.26979698e-03, -3.30082355e-02],
         [-3.66229278e-03,  2.05285929e-03,  1.75241015e-03, ...,
          -4.59145499e-03, -4.28575878e-02, -7.67948801e-03],
         [ 3.98177919e-03, -1.55957601e-02, -1.49061857e-02, ...,
          -4.55224361e-02,  3.44636341e-03,  1.62040837e-03]]),
  'original_stats': column             highlights
  overall_mean        -0.015794
  overall_std          0.013166
  std_of_means         0.194579
  mean_of_medians     -0.015867
  asymmetry_avg        0.011107
  excess_avg           0.363758
  n_entries               11490
  vector_dim                300
  Name: 1, dtype: object}]